create extension if not exists pgcrypto;

create type public.application_status as enum ('new','reviewing','shortlisted','interview','offered','hired','rejected','withdrawn');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'interviewer' check(role in ('admin','hr','interviewer')), created_at timestamptz not null default now());
create table public.jobs (id text primary key, slug text unique not null, department text not null, location text not null, employment_type text not null default 'Full-time', vacancies integer not null default 1, level text, salary_text text, application_deadline date, title jsonb not null, summary jsonb not null, responsibilities jsonb not null default '{}', requirements jsonb not null default '{}', benefits jsonb not null default '{}', status text not null default 'draft' check(status in ('draft','published','closed','archived')), published_at timestamptz, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.applications (id uuid primary key default gen_random_uuid(), job_id text not null references public.jobs(id) on delete restrict, job_title text not null, full_name text not null, email text not null, phone text not null, experience_years int, cover_note text, cv_path text not null, locale text not null default 'vi', status public.application_status not null default 'new', rating smallint check(rating between 1 and 5), hr_notes text, consent_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.application_events (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.applications(id) on delete cascade, actor_id uuid references public.profiles(id), event_type text not null, from_status public.application_status, to_status public.application_status, note text, created_at timestamptz not null default now());
create table public.email_logs (id uuid primary key default gen_random_uuid(), application_id uuid references public.applications(id) on delete set null, template_key text not null, recipient text not null, provider_id text, status text not null, sent_by uuid references public.profiles(id), created_at timestamptz not null default now());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('candidate-cvs','candidate-cvs',false,5242880,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']) on conflict(id) do nothing;
alter table public.profiles enable row level security; alter table public.jobs enable row level security; alter table public.applications enable row level security; alter table public.application_events enable row level security; alter table public.email_logs enable row level security;
create or replace function public.current_staff_role() returns text language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() $$;
create policy "public can read published jobs" on public.jobs for select using(status='published');
create policy "staff can read profiles" on public.profiles for select to authenticated using(public.current_staff_role() in('admin','hr','interviewer'));
create policy "hr manages jobs" on public.jobs for all to authenticated using(public.current_staff_role() in('admin','hr')) with check(public.current_staff_role() in('admin','hr'));
create policy "staff reads applications" on public.applications for select to authenticated using(public.current_staff_role() in('admin','hr','interviewer'));
create policy "staff writes events" on public.application_events for insert to authenticated with check(public.current_staff_role() in('admin','hr','interviewer'));
create policy "staff reads events" on public.application_events for select to authenticated using(public.current_staff_role() in('admin','hr','interviewer'));
create policy "staff writes email logs" on public.email_logs for insert to authenticated with check(public.current_staff_role() in('admin','hr'));
create policy "staff reads email logs" on public.email_logs for select to authenticated using(public.current_staff_role() in('admin','hr','interviewer'));
create policy "staff reads private cvs" on storage.objects for select to authenticated using(bucket_id='candidate-cvs' and public.current_staff_role() in('admin','hr','interviewer'));
