import { notFound } from "next/navigation";
import { PageHero } from "@/components/PageHero";
import { isLocale } from "@/lib/i18n";

const content={
  vi:{title:"Thông báo quyền riêng tư ứng viên",lead:"Cách YMX Việt Nam thu thập và sử dụng thông tin trong quá trình tuyển dụng.",sections:[["Thông tin được thu thập","Thông tin liên hệ, kinh nghiệm, học vấn, nội dung CV, ghi chú phỏng vấn và các thông tin ứng viên chủ động cung cấp."],["Mục đích xử lý","Đánh giá mức độ phù hợp, liên hệ ứng viên, tổ chức phỏng vấn, thông báo kết quả và thực hiện các bước tuyển dụng."],["Quyền truy cập","Hồ sơ chỉ được truy cập bởi nhân sự tuyển dụng và người phỏng vấn được phân quyền. CV được lưu trong vùng riêng tư và liên kết tải xuống có thời hạn."],["Lưu trữ và quyền của ứng viên","Hồ sơ được lưu trong thời gian cần thiết cho mục đích tuyển dụng và nghĩa vụ pháp lý. Ứng viên có thể liên hệ YMX để yêu cầu cập nhật hoặc xóa thông tin theo quy định áp dụng."]]},
  en:{title:"Candidate privacy notice",lead:"How YMX Vietnam collects and uses information during recruitment.",sections:[["Information we collect","Contact details, experience, education, CV content, interview notes and information voluntarily provided by the candidate."],["Why we process it","To assess suitability, contact candidates, arrange interviews, communicate results and complete recruitment steps."],["Who can access it","Only authorized recruitment staff and interviewers. CVs are stored privately and download links expire."],["Retention and candidate rights","Records are retained only as necessary for recruitment and legal obligations. Candidates may contact YMX to request correction or deletion where applicable."]]},
  zh:{title:"应聘者隐私声明",lead:"越南YMX在招聘过程中如何收集和使用个人信息。",sections:[["收集的信息","联系方式、工作经验、教育背景、简历内容、面试记录及应聘者主动提供的信息。"],["处理目的","用于评估岗位匹配度、联系应聘者、安排面试、通知结果及完成招聘流程。"],["访问权限","仅获授权的招聘人员和面试官可访问。简历保存在私有存储中，下载链接具有有效期限。"],["保存期限与权利","资料仅在招聘及法律义务所需期限内保存。应聘者可联系YMX申请更正或删除资料。"]]},
} as const;
export default async function Privacy({params}:{params:Promise<{lang:string}>}){const {lang}=await params;if(!isLocale(lang))notFound();const c=content[lang];return <main><PageHero kicker="Privacy" title={c.title} text={c.lead}/><section className="section"><div className="container privacy-content">{c.sections.map(([title,text])=><article key={title}><h2>{title}</h2><p>{text}</p></article>)}</div></section></main>}
