import type { Locale } from "./i18n";

export const publicCopy={
vi:{
 aboutParas:["YMX Việt Nam là dự án sản xuất 100% vốn đầu tư nước ngoài thuộc sở hữu của Hongkong YMX Electronic Co., Limited, tập trung vào gia công cắt bế chính xác vật liệu điện tử cao cấp.","Dây chuyền tích hợp gồm cắt cuộn, cắt bế, cán màng và dập khuôn, được hỗ trợ bởi hệ thống đo lường và kiểm tra đồng bộ."],profile:"Thông tin doanh nghiệp",businessId:"Mã số doanh nghiệp",factory:"Nhà máy",capacity:"Công suất",facility:"Diện tích",productLead:"Giải pháp vật liệu chính xác cho điện tử, di động và các ứng dụng công nghiệp tiên tiến.",productDesc:"Linh kiện cắt bế chính xác theo yêu cầu, được thiết kế cho sản xuất ổn định và hiệu suất tin cậy.",equipmentLead:"Thiết bị sản xuất và đo lường tích hợp, vận hành theo hướng dẫn công việc tiêu chuẩn.",equipmentDesc:"Quy trình được kiểm soát, bảo dưỡng phòng ngừa và đội ngũ được đào tạo giúp duy trì đầu ra ổn định.",qualityKicker:"Vận hành xuất sắc",qualityLead:"Chất lượng, an toàn, sức khỏe và trách nhiệm môi trường được tích hợp trong mọi công đoạn vận hành.",qualityDesc:"Kiểm soát tiêu chuẩn, bằng chứng hồ sơ và cải tiến liên tục trong toàn nhà máy.",contactLead:"Trao đổi với YMX về gia công cắt bế chính xác, hợp tác sản xuất hoặc cơ hội nghề nghiệp.",factoryAddress:"Địa chỉ nhà máy",phone:"Điện thoại",phoneHelp:"Liên hệ văn phòng để được hỗ trợ",careerProcess:"Quy trình minh bạch, đánh giá có cấu trúc và trao đổi tôn trọng trong suốt hành trình ứng tuyển.",responsibilities:"Trách nhiệm công việc",requirements:"Yêu cầu",expect:"Quyền lợi và môi trường",expectText:"Môi trường sản xuất chuyên nghiệp, đào tạo hội nhập rõ ràng, đánh giá công bằng và cơ hội phát triển trong mạng lưới sản xuất quốc tế.",completeForm:"Hoàn thành biểu mẫu và đính kèm CV mới nhất của bạn."},
en:{
 aboutParas:["YMX Vietnam is a 100% foreign-invested manufacturing project owned by Hongkong YMX Electronic Co., Limited, focused on precision die-cutting for advanced electronic materials.","Our integrated production includes slitting, die-cutting, laminating and stamping, supported by a complete measurement and testing system."],profile:"Company profile",businessId:"Business ID",factory:"Factory",capacity:"Capacity",facility:"Facility",productLead:"Precision material solutions for electronics, mobility and advanced industrial applications.",productDesc:"Custom precision die-cut components engineered for stable production and reliable performance.",equipmentLead:"Integrated production and measurement equipment operated under standardized work instructions.",equipmentDesc:"Controlled processes, preventive maintenance and trained operators support consistent output.",qualityKicker:"Operational excellence",qualityLead:"Quality, safety, health and environmental responsibility are built into every stage of our operation.",qualityDesc:"Standardized control, documented evidence and continuous improvement across the factory.",contactLead:"Talk to our team about precision die-cutting, manufacturing partnerships or career opportunities.",factoryAddress:"Factory address",phone:"Phone",phoneHelp:"Contact our office for assistance",careerProcess:"Transparent recruitment, structured review and respectful communication throughout your candidate journey.",responsibilities:"Responsibilities",requirements:"Requirements",expect:"What you can expect",expectText:"A professional manufacturing environment, clear onboarding, fair evaluation and opportunities to develop with an international production network.",completeForm:"Complete the form and attach your latest CV."},
zh:{
 aboutParas:["越南YMX是由香港YMX电子有限公司投资的外资制造项目，专注于高端电子材料的精密模切加工。","一体化生产涵盖分切、模切、覆膜及冲压，并配套完整的测量与检测系统。"],profile:"企业信息",businessId:"企业代码",factory:"工厂",capacity:"年产能",facility:"厂房面积",productLead:"为电子、移动及先进工业应用提供精密材料解决方案。",productDesc:"按客户要求制造精密模切零部件，确保稳定生产和可靠性能。",equipmentLead:"按照标准作业指导书运行的一体化生产与测量设备。",equipmentDesc:"受控流程、预防性维护及专业培训确保稳定产出。",qualityKicker:"卓越运营",qualityLead:"质量、安全、健康与环境责任贯穿生产运营的每个环节。",qualityDesc:"全厂实施标准化控制、文件记录及持续改进。",contactLead:"欢迎联系YMX洽谈精密模切、生产合作或职业机会。",factoryAddress:"工厂地址",phone:"电话",phoneHelp:"请联系办公室获取协助",careerProcess:"透明的招聘流程、结构化评估，并在整个应聘过程中保持尊重沟通。",responsibilities:"工作职责",requirements:"任职要求",expect:"工作环境与发展",expectText:"专业的制造环境、清晰的入职培训、公平的评估及国际生产网络中的发展机会。",completeForm:"请填写表格并上传您的最新简历。"}
} as const;

export const productNames:Record<Locale,string[]>={vi:["Máy in / Photocopy","Điện thoại di động","Máy tính xách tay","Module đèn nền","Ô tô / Pin","Ứng dụng khác"],en:["Printer / Copier","Mobile phone","Notebook","Backlight module","Automobile / Battery","Other applications"],zh:["打印机 / 复印机","手机","笔记本电脑","背光模组","汽车 / 电池","其他应用"]};
export const equipmentNames:Record<Locale,string[]>={vi:["Máy xẻ rãnh","Máy cắt cuộn","Máy cắt khuôn","Máy cán màng","Dây chuyền cán màng mới","Máy đo VMM 2D","Máy thử lực kéo"],en:["Slitting machine","Roll cutting machine","Die-cutting machine","Laminating machine","Advanced laminating line","VMM 2D measuring","Tensile testing machine"],zh:["开槽机","卷材切割机","模切机","覆膜机","新型覆膜线","VMM二维测量仪","拉力试验机"]};
export function pc(locale:Locale){return publicCopy[locale]}
